version: '3.8'
services:
  mongodb:
    image: mongo:4.4.21
    container_name: mongo4
    environment:
      - MONGO_INITDB_DATABASE=monitor
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./mongo:/data/db
    ports:
      - '27017:27017'
    restart: always
